-- Consent na úrovni pageview: pageview = EVENT_DATE_UTC + USER_PSEUDO_ID + PAGE_LOCATION_CLEAN
-- Pokud měl uživatel na dané stránce v daný den alespoň 1 event s CONSENT_ANALYTICS_STORAGE = TRUE, je Granted, jinak Denied
SELECT
  DATE(EVENT_DATE_UTC) AS EVENT_DATE,
  PAGE_LOCATION_CLEAN,
  DEVICE_CATEGORY,
  CONTENT_GROUP,
  USER_PSEUDO_ID,
  CASE
    WHEN LOGICAL_OR(CONSENT_ANALYTICS_STORAGE IS TRUE) THEN "Granted"
    ELSE "Denied"
  END AS CONSENT_ANALYTICS_STORAGE
FROM
  `collectorboycz.UserTracking.RAW_DATA_PROD`
WHERE
  EVENT_DATE_UTC BETWEEN "2024-04-01" AND CURRENT_DATE()
  AND TRAFFIC_TYPE != "internal"
  AND PAGE_LOCATION_CLEAN IS NOT NULL
  AND NOT REGEXP_CONTAINS(
    LOWER(USER_AGENT),
    (SELECT STRING_AGG(PATTERN, '|') FROM `collectorboycz.UserTracking.BOT_USER_AGENTS` WHERE IS_ACTIVE)
  )
GROUP BY
  EVENT_DATE,
  PAGE_LOCATION_CLEAN,
  USER_PSEUDO_ID,
  DEVICE_CATEGORY,
  CONTENT_GROUP
ORDER BY
  EVENT_DATE ASC,
  PAGE_LOCATION_CLEAN,
  DEVICE_CATEGORY,
  CONTENT_GROUP