-- Consent na úrovni session: session = USER_PSEUDO_ID + GA_SESSION_ID
-- Pokud má tato session alespoň 1 event s CONSENT_ANALYTICS_STORAGE = TRUE, je Granted, jinak Denied
SELECT
  DATE(EVENT_DATE_UTC) AS EVENT_DATE,
  CONCAT(USER_PSEUDO_ID, "-", GA_SESSION_ID) AS UNIQUE_SESSION_ID,
  DEVICE_CATEGORY,
  USER_PSEUDO_ID,
  CASE
    WHEN LOGICAL_OR(CONSENT_ANALYTICS_STORAGE IS TRUE) THEN "Granted"
    ELSE "Denied"
  END AS CONSENT_ANALYTICS_STORAGE
FROM
  `collectorboycz.UserTracking.RAW_DATA_PROD`
WHERE
  EVENT_DATE_UTC BETWEEN "2024-04-01" AND CURRENT_DATE()
  AND TRAFFIC_TYPE != "internal"
  AND NOT REGEXP_CONTAINS(
    LOWER(USER_AGENT),
    (SELECT STRING_AGG(PATTERN, '|') FROM `collectorboycz.UserTracking.BOT_USER_AGENTS` WHERE IS_ACTIVE)
  )
GROUP BY
  EVENT_DATE,
  UNIQUE_SESSION_ID,
  DEVICE_CATEGORY,
  USER_PSEUDO_ID
ORDER BY
  EVENT_DATE ASC,
  DEVICE_CATEGORY,
  UNIQUE_SESSION_ID